//! 1- Function to sign up a user:
export const signUpUser = async (req, res, next) => {
  try {
  } catch (error) {
    console.error("Error in sign up user controller:", error);
    next(error);
  }
};

//! 2- Function to log in a user:
export const logInUser = async (req, res, next) => {
  try {
  } catch (error) {
    console.error("Error in log in user controller:", error);
    next(error);
  }
};

//! 3- Function to log out a user:
export const logOutUser = async (req, res, next) => {
  try {
  } catch (error) {
    console.error("Error in log out user controller:", error);
    next(error);
  }
};
